---
galaxy_info:
  author: Philipp Wegner
  description: Switches Proxmox apt repositories from enterprise to no-subscription and updates the apt cache
  license: MIT
  min_ansible_version: '2.14'
  platforms:
    - name: Debian
      versions:
        - bookworm

dependencies: []
