---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-vip
      version: '0.7.x'
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: kube-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      vip_interface: eth0
      vip_leaderelection: true
    env:
      cp_enable: 'true'
      svc_enable: 'false'
      vip_arp: 'true'
