---

all:
  children:
    # ===============================================
    # Localhost
    # ===============================================
    localhost_group:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: 127.0.0.1
          ansible_user: "your_local_user"

    # ===============================================
    # Proxmox Nodes (Debian-based)
    # ===============================================
    proxmox_nodes:
      hosts:
        pve01:
          ansible_host: "10.10.10.10"
        pve02:
          ansible_host: "10.10.10.20"
        pve03:
          ansible_host: "10.10.10.30"

      vars:
        ansible_user: root

    pve_cluster_01:
      children:
        proxmox_nodes: {}

    proxmox_cluster:
      children:
        pve_cluster_01: {}

    # ===============================================
    # NixOS Core Services
    # ===============================================
    admin_vms:
      hosts:
        admin-01:
          ansible_host: "10.1.1.1"

    gitlab_vms:
      hosts:
        git-01:
          ansible_host: "10.50.1.10"

    # ===============================================
    # NixOS Common Services
    # ===============================================
    docker_vms:
      hosts:
        docker-01:
          ansible_host: "10.80.1.10"

    common_vms:
      hosts:
        vm-template:
          ansible_host: "10.199.99.1"

    # ===============================================
    # Talos Kubernetes Nodes
    # ===============================================
    talos_control_plane:
      hosts:
        k8s-cp-01:
          ansible_host: "10.90.5.100"
        k8s-cp-02:
          ansible_host: "10.90.5.101"
        k8s-cp-03:
          ansible_host: "10.90.5.102"
    talos_workers:
      hosts:
        k8s-worker-01:
          ansible_host: "10.90.10.100"
        k8s-worker-02:
          ansible_host: "10.90.10.101"
        k8s-worker-03:
          ansible_host: "10.90.10.102"
    talos:
      children:
        talos_control_plane: {}
        talos_workers: {}

    # ===============================================
    # Logical Groups
    # ===============================================
    nixos_vms:
      children:
        admin_vms: {}
        gitlab_vms: {}
        docker_vms: {}
        common_vms: {}

    core_services:
      children:
        admin_vms: {}
        gitlab_vms: {}

    all_services:
      children:
        core_services: {}
        docker_vms: {}
        common_vms: {}
