---
galaxy_info:
  author: Philipp Wegner
  description: Sets up SOPS/age secret management on both the controller (localhost) and remote NixOS hosts
  license: MIT
  min_ansible_version: '2.14'
  platforms:
    - name: GenericLinux
      versions:
        - all

dependencies: []
